; -------------------- Single Key --------------------
if(!keyMap.Has("caps_a"))
	keyMap["caps_a"]:="key_doNothing"
if(!keyMap.Has("caps_b"))
	keyMap["caps_b"]:="key_bs"
if(!keyMap.Has("caps_c"))
	keyMap["caps_c"]:="key_doNothing"
if(!keyMap.Has("caps_d"))
	keyMap["caps_d"]:="key_deleteLine"
if(!keyMap.Has("caps_e"))
	keyMap["caps_e"]:="key_doNothing"
if(!keyMap.Has("caps_f"))
	keyMap["caps_f"]:="key_doNothing"
if(!keyMap.Has("caps_g"))
	keyMap["caps_g"]:="key_doNothing"
if(!keyMap.Has("caps_h"))
	keyMap["caps_h"]:="key_moveLeft"
if(!keyMap.Has("caps_i"))
	keyMap["caps_i"]:="key_doNothing"
if(!keyMap.Has("caps_j"))
	keyMap["caps_j"]:="key_moveDown"
if(!keyMap.Has("caps_k"))
	keyMap["caps_k"]:="key_moveUp"
if(!keyMap.Has("caps_l"))
	keyMap["caps_l"]:="key_moveRight"
if(!keyMap.Has("caps_m"))
	keyMap["caps_m"]:="key_doNothing"
if(!keyMap.Has("caps_n"))
	keyMap["caps_n"]:="key_doNothing"
if(!keyMap.Has("caps_o"))
	keyMap["caps_o"]:="key_doNothing"
if(!keyMap.Has("caps_p"))
	keyMap["caps_p"]:="key_moveRightWord"
if(!keyMap.Has("caps_q"))
	keyMap["caps_q"]:="key_doNothing"
if(!keyMap.Has("caps_r"))
	keyMap["caps_r"]:="key_doNothing"
if(!keyMap.Has("caps_s"))
	keyMap["caps_s"]:="key_doNothing"
if(!keyMap.Has("caps_t"))
	keyMap["caps_t"]:="key_doNothing"
if(!keyMap.Has("caps_u"))
	keyMap["caps_u"]:="key_moveLeftWord"
if(!keyMap.Has("caps_v"))
	keyMap["caps_v"]:="key_doNothing"
if(!keyMap.Has("caps_w"))
	keyMap["caps_w"]:="hideWindow"
if(!keyMap.Has("caps_x"))
	keyMap["caps_x"]:="key_del"
if(!keyMap.Has("caps_y"))
	keyMap["caps_y"]:="key_home"
if(!keyMap.Has("caps_z"))
	keyMap["caps_z"]:="key_doNothing"

if(!keyMap.Has("caps_``"))
	keyMap["caps_``"]:="key_graveAccent"
if(!keyMap.Has("caps_["))
	keyMap["caps_["]:="key_squareBracket"
if(!keyMap.Has("caps_;"))
	keyMap["caps_;"]:="key_end"
if(!keyMap.Has("caps_'"))
	keyMap["caps_'"]:="key_singleQuote"
if(!keyMap.Has("caps_Enter"))
	keyMap["caps_Enter"]:="key_enter"
if(!keyMap.Has("caps_esc"))
	keyMap["caps_esc"]:="exitScript"
if(!keyMap.Has("caps_F2"))
	keyMap["caps_F2"]:="editScript"
if(!keyMap.Has("caps_F5"))
	keyMap["caps_F5"]:="reloadScript"

if(!keyMap.Has("caps_1"))
	keyMap["caps_1"]:="activeWin(1)"
if(!keyMap.Has("caps_2"))
	keyMap["caps_2"]:="activeWin(2)"
if(!keyMap.Has("caps_3"))
	keyMap["caps_3"]:="activeWin(3)"
if(!keyMap.Has("caps_4"))
	keyMap["caps_4"]:="activeWin(4)"
if(!keyMap.Has("caps_5"))
	keyMap["caps_5"]:="activeWin(5)"

; -------------------- Alt --------------------
if(!keyMap.Has("caps_!h"))
	keyMap["caps_!h"]:="key_altLeft"
if(!keyMap.Has("caps_!j"))
	keyMap["caps_!j"]:="key_altDown"
if(!keyMap.Has("caps_!k"))
	keyMap["caps_!k"]:="key_altUp"
if(!keyMap.Has("caps_!l"))
	keyMap["caps_!l"]:="key_altRight"
if(!keyMap.Has("caps_!w"))
	keyMap["caps_!w"]:="displayHiddenWindowList"

; -------------------- Ctrl --------------------
if(!keyMap.Has("caps_^h"))
	keyMap["caps_^h"]:="key_ctrlLeft"
if(!keyMap.Has("caps_^j"))
	keyMap["caps_^j"]:="key_ctrlDown"
if(!keyMap.Has("caps_^k"))
	keyMap["caps_^k"]:="key_ctrlUp"
if(!keyMap.Has("caps_^l"))
	keyMap["caps_^l"]:="key_ctrlRight"

if(!keyMap.Has("caps_^b"))
	keyMap["caps_^b"]:="key_bs_word"
if(!keyMap.Has("caps_^x"))
	keyMap["caps_^x"]:="key_del_word"
if(!keyMap.Has("caps_^1"))
	keyMap["caps_^1"]:="storeWin(1)"
if(!keyMap.Has("caps_^2"))
	keyMap["caps_^2"]:="storeWin(2)"
if(!keyMap.Has("caps_^3"))
	keyMap["caps_^3"]:="storeWin(3)"
if(!keyMap.Has("caps_^4"))
	keyMap["caps_^4"]:="storeWin(4)"
if(!keyMap.Has("caps_^5"))
	keyMap["caps_^5"]:="storeWin(5)"

if(!keyMap.Has("caps_^F5"))
	keyMap["caps_^F5"]:="key_mediaPause"
if(!keyMap.Has("caps_^Up"))
	keyMap["caps_^Up"]:="key_volumeUp"
if(!keyMap.Has("caps_^Down"))
	keyMap["caps_^Down"]:="key_volumeDown"
if(!keyMap.Has("caps_^Left"))
	keyMap["caps_^Left"]:="key_mediaPrev"
if(!keyMap.Has("caps_^Right"))
	keyMap["caps_^Right"]:="key_mediaNext"

; -------------------- Shift --------------------
if(!keyMap.Has("caps_+a"))
	keyMap["caps_+a"]:="doNothing"
if(!keyMap.Has("caps_+b"))
	keyMap["caps_+b"]:="doNothing"
if(!keyMap.Has("caps_+c"))
	keyMap["caps_+c"]:="doNothing"
if(!keyMap.Has("caps_+d"))
	keyMap["caps_+d"]:="doNothing"
if(!keyMap.Has("caps_+e"))
	keyMap["caps_+e"]:="doNothing"
if(!keyMap.Has("caps_+f"))
	keyMap["caps_+f"]:="doNothing"
if(!keyMap.Has("caps_+g"))
	keyMap["caps_+g"]:="doNothing"
if(!keyMap.Has("caps_+h"))
	keyMap["caps_+h"]:="key_selectLeft"
if(!keyMap.Has("caps_+i"))
	keyMap["caps_+i"]:="doNothing"
if(!keyMap.Has("caps_+j"))
	keyMap["caps_+j"]:="key_selectDown"
if(!keyMap.Has("caps_+k"))
	keyMap["caps_+k"]:="key_selectUp"
if(!keyMap.Has("caps_+l"))
	keyMap["caps_+l"]:="key_selectRight"
if(!keyMap.Has("caps_+m"))
	keyMap["caps_+m"]:="doNothing"
if(!keyMap.Has("caps_+n"))
	keyMap["caps_+n"]:="doNothing"
if(!keyMap.Has("caps_+o"))
	keyMap["caps_+o"]:="doNothing"
if(!keyMap.Has("caps_+p"))
	keyMap["caps_+p"]:="key_selectRightWord"
if(!keyMap.Has("caps_+q"))
	keyMap["caps_+q"]:="doNothing"
if(!keyMap.Has("caps_+r"))
	keyMap["caps_+r"]:="doNothing"
if(!keyMap.Has("caps_+s"))
	keyMap["caps_+s"]:="doNothing"
if(!keyMap.Has("caps_+t"))
	keyMap["caps_+t"]:="doNothing"
if(!keyMap.Has("caps_+u"))
	keyMap["caps_+u"]:="key_selectLeftWord"
if(!keyMap.Has("caps_+v"))
	keyMap["caps_+v"]:="doNothing"
if(!keyMap.Has("caps_+w"))
	keyMap["caps_+w"]:="displayAllHiddenWindows"
if(!keyMap.Has("caps_+x"))
	keyMap["caps_+x"]:="doNothing"
if(!keyMap.Has("caps_+y"))
	keyMap["caps_+y"]:="key_selectHome"
if(!keyMap.Has("caps_+z"))
	keyMap["caps_+z"]:="doNothing"

if(!keyMap.Has("caps_+;"))
	keyMap["caps_+;"]:="key_selectEnd"
if(!keyMap.Has("caps_+'"))
	keyMap["caps_+'"]:="key_doubleQuote"
if(!keyMap.Has("caps_+,"))
	keyMap["caps_+,"]:="key_angleBracket"
if(!keyMap.Has("caps_+9"))
	keyMap["caps_+9"]:="key_parenthesis"
if(!keyMap.Has("caps_+["))
	keyMap["caps_+["]:="key_brace"
; -------------------- Ctrl + Alt --------------------
if(!keyMap.Has("caps_^!h"))
	keyMap["caps_^!h"]:="key_ctrlAltLeft"
if(!keyMap.Has("caps_^!j"))
	keyMap["caps_^!j"]:="key_ctrlAltDown"
if(!keyMap.Has("caps_^!k"))
	keyMap["caps_^!k"]:="key_ctrlAltUp"
if(!keyMap.Has("caps_^!l"))
	keyMap["caps_^!l"]:="key_ctrlAltRight"

; -------------------- Ctrl + Shift --------------------
if(!keyMap.Has("caps_^+h"))
	keyMap["caps_^+h"]:="key_ctrlShiftLeft"
if(!keyMap.Has("caps_^+j"))
	keyMap["caps_^+j"]:="key_ctrlShiftDown"
if(!keyMap.Has("caps_^+k"))
	keyMap["caps_^+k"]:="key_ctrlShiftUp"
if(!keyMap.Has("caps_^+l"))
	keyMap["caps_^+l"]:="key_ctrlShiftRight"

; -------------------- Shift + Alt --------------------
if(!keyMap.Has("caps_+!h"))
	keyMap["caps_+!h"]:="key_shiftAltLeft"
if(!keyMap.Has("caps_+!j"))
	keyMap["caps_+!j"]:="key_shiftAltDown"
if(!keyMap.Has("caps_+!k"))
	keyMap["caps_+!k"]:="key_shiftAltUp"
if(!keyMap.Has("caps_+!l"))
	keyMap["caps_+!l"]:="key_shiftAltRight"

; -------------------- Ctrl + Shift + Alt --------------------

